name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '7,27,47 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl https://kubra.io/data/d14e25f3-4df1-4c8a-8042-189ec230aa00/public/reports/52237999-88c8-40c3-9a5c-61117b9b0719_report.json | jq .file_data > incidents.json
        curl https://kubra.io/data/3f37c7e5-a7a5-416c-aa33-994f56d038d5/public/summary-1/data.json | jq . > incidents_overview.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
